Issue/423
OpenHFT/Chronicle-Map pull request #424
Opened 2022-05-16 14:22 UTC by minborg

2022-05-16 14:22 UTC, minborg commented on src/main/java/net/openhft/chronicle/hash/impl/util/CanonicalRandomAccessFiles.java
> +        return acquire0(file, (ref) -> {
Reformatted by IntelliJ. Should we revert?

2022-05-18 09:48 UTC, RobAustin approved these changes

2022-05-18 09:49 UTC, alamar requested changes
Does this issue only trigger on Windows? I can't see the reproducer to fail. Otherwise, it makes sense.

2022-05-18 09:49 UTC, alamar commented on src/main/java/net/openhft/chronicle/hash/impl/util/CanonicalRandomAccessFiles.java
> +        return acquire0(file, (ref) -> {
Maybe we need some reusable empty consumer?

2022-05-18 09:49 UTC, alamar commented on src/test/java/net/openhft/chronicle/map/issue/Issue423Test.java
> +public class Issue423Test {
I suggest having a descriptive name. Issue is visible in commit message anyway

2022-05-18 09:50 UTC, alamar requested changes

2022-05-18 09:50 UTC, alamar commented on src/main/java/net/openhft/chronicle/hash/impl/util/CanonicalRandomAccessFiles.java
> +        });
If you must keep it reformatted you could add `// No-op.` comment

2022-05-18 11:19 UTC, alamar approved these changes

2022-05-18 11:22 UTC, merged

2022-05-18 23:39 UTC, JerryShea commented on .gitignore
> +issue423
why?

2022-05-18 23:39 UTC, JerryShea commented on src/test/java/net/openhft/chronicle/map/issue/Issue423LockFileRemainsLockedOnWindowsIfBuilderThrowsTest.java
> +        assertTrue(file.delete());
this should be in a finally?

2022-05-18 23:40 UTC, JerryShea commented on src/test/java/net/openhft/chronicle/map/issue/Issue423LockFileRemainsLockedOnWindowsIfBuilderThrowsTest.java
> +        final File file = new File("issue423");
maybe put in OS.target() so it does not clutter the directory

2022-05-19 07:33 UTC, minborg commented on src/test/java/net/openhft/chronicle/map/issue/Issue423LockFileRemainsLockedOnWindowsIfBuilderThrowsTest.java
> +        final File file = new File("issue423");
Good suggestion

2022-05-19 07:34 UTC, minborg commented on src/test/java/net/openhft/chronicle/map/issue/Issue423LockFileRemainsLockedOnWindowsIfBuilderThrowsTest.java
> +        assertTrue(file.delete());
That would have been better, yes.